ForumDigitalParadise/Controllers/ProfileController.cs
using ForumDigitalParadise.Data;
using ForumDigitalParadise.Data.Models;
using ForumDigitalParadise.Data.Services;
using ForumDigitalParadise.Models.ApplicationUser;
using ForumDigitalParadise.Models.Post;
using ForumDigitalParadise.Service;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace ForumDigitalParadise.Controllers
{
   
    public class ProfileController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IApplicationUser _userService;
        private readonly IUpload _uploadService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IPost _postService;
        private readonly IPostLike _postLikeService;
        private readonly IPostReply _postReplyService;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public ProfileController(UserManager<ApplicationUser> userManager, IApplicationUser userService, IUpload uploadService, IWebHostEnvironment webHostEnvironment, IPost postService, IPostReply postReplyService, SignInManager<ApplicationUser> signInManager, IPostLike postLikeService)
        {
            _userManager = userManager;
            _userService = userService;
            _uploadService = uploadService;
            _webHostEnvironment = webHostEnvironment;
            _postService = postService;
            _postReplyService = postReplyService;
            _signInManager = signInManager;
            _postLikeService = postLikeService;
        }
        [Authorize]
        public IActionResult Settings(string id)
        {
            var user = _userService.GetById(id);
            if (user == null)
            {
                return NotFound();
            }

            var userRoles = _userManager.GetRolesAsync(user).Result;
            var webrootpathUser = "~/img/ProfileImages/";
            var webrootpathBanner = "~/img/BannerImages/";
            var model = new SettingsModel()
            {
                UserId = user.Id,
                UserName = user.UserName,
                DisplayName = user.DisplayName, 
                Email = user.Email,
                ProfileImageUrl = string.IsNullOrEmpty(user.ProfileImageUrl) ? "~/img/users/default_image.jpg" : webrootpathUser + user.ProfileImageUrl,
                BannerImageUrl = webrootpathBanner + user.BannerImageUrl,
                MemberSince = user.MemberSince,
                IsAdmin = userRoles.Contains("Admin"),
                IsActive = user.IsActive
            };

            return View(model);
        }
        [Authorize]
        [HttpPost]
        public async Task<IActionResult> UpdateProfile(string UserName, string DisplayName, string UserDescription)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound("User not found");
            }

            if (!string.IsNullOrEmpty(DisplayName))
            {
                user.DisplayName = DisplayName;
            }

            if (!string.IsNullOrEmpty(UserDescription))
            {
                user.UserDescription = UserDescription;
            }

            var result = await _userManager.UpdateAsync(user);

            if (result.Succeeded)
            {
                return Ok(new { success = true });
            }

            return BadRequest(new { success = false, errors = result.Errors });
        }

        public async Task<IActionResult> Overview(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var isOwner = currentUser != null && currentUser.Id == user.Id;

            var userRoles = await _userManager.GetRolesAsync(user);

            var webrootpathUser = "~/img/ProfileImages/";
            var webrootpathBanner = "~/img/BannerImages/";
            var webrootpathPost = "~/img/PostImages/";

            var posts = _postService.GetPostsByUserId(user.Id);
            var replies = _postReplyService.GetRepliesByUserId(user.Id);

            var postListingModels = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                Title = post.Title,
                PostContent = post.Content,
                PostImageUrl = string.IsNullOrEmpty(post.ImageUrl) ? null : webrootpathPost + post.ImageUrl,
                Created = post.Created,
                Views = post.Views,
                RepliesCount = post.Replies.Count(),
                LikesCount = post.Likes.Count()
            }).ToList();

            var model = new ProfileModel
            {
                Id = user.Id,
                UserId = user.Id,
                UserName = user.UserName,
                DisplayName = user.DisplayName,
                UserRating = user.Rating.ToString(),
                UserCommentRating = user.CommentRating.ToString(),
                UserPostRating = user.PostRating.ToString(),
                UserDescription = user.UserDescription,
                ProfileImageUrl = string.IsNullOrEmpty(user.ProfileImageUrl) ? "~/img/users/default_image.jpg" : webrootpathUser + user.ProfileImageUrl,
                BannerImageUrl = string.IsNullOrEmpty(user.BannerImageUrl) ? null : webrootpathBanner + user.BannerImageUrl,
                MemberSince = user.MemberSince,
                IsAdmin = userRoles.Contains("Admin"),
                Posts = postListingModels,
                Replies = replies,
                IsOwner = isOwner
            };

            return View(model);
        }


        public async Task<IActionResult> Comments(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var isOwner = currentUser != null && currentUser.Id == user.Id;

            var userRoles = await _userManager.GetRolesAsync(user);

            var webrootpathUser = "~/img/ProfileImages/";
            var webrootpathBanner = "~/img/BannerImages/";
            var webrootpathPost = "~/img/PostImages/";

            var posts = _postService.GetPostsByUserId(user.Id);
            var replies = _postReplyService.GetRepliesByUserId(user.Id);

            var postListingModels = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                Title = post.Title,
                PostContent = post.Content,
                PostImageUrl = string.IsNullOrEmpty(post.ImageUrl) ? null : webrootpathPost + post.ImageUrl,
                Created = post.Created,
                Views = post.Views,
                RepliesCount = post.Replies.Count()
            }).ToList();

            var model = new ProfileModel
            {
                Id = user.Id,
                UserId = user.Id,
                UserName = user.UserName,
                DisplayName = user.DisplayName,
                UserRating = user.Rating.ToString(),
                UserCommentRating = user.CommentRating.ToString(),
                UserPostRating = user.PostRating.ToString(),
                UserDescription = user.UserDescription,
                ProfileImageUrl = string.IsNullOrEmpty(user.ProfileImageUrl) ? "~/img/users/default_image.jpg" : webrootpathUser + user.ProfileImageUrl,
                BannerImageUrl = string.IsNullOrEmpty(user.BannerImageUrl) ? null : webrootpathBanner + user.BannerImageUrl,
                MemberSince = user.MemberSince,
                IsAdmin = userRoles.Contains("Admin"),
                Posts = postListingModels,
                Replies = replies,
                IsOwner = isOwner
            };

            return View(model);
        }

        public async Task<IActionResult> Posts(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            var currentUser = await _userManager.GetUserAsync(User);
            var isOwner = currentUser != null && currentUser.Id == user.Id;

            var userRoles = await _userManager.GetRolesAsync(user);

            var webrootpathUser = "~/img/ProfileImages/";
            var webrootpathBanner = "~/img/BannerImages/";
            var webrootpathPost = "~/img/PostImages/";

            var posts = _postService.GetPostsByUserId(user.Id);
            var replies = _postReplyService.GetRepliesByUserId(user.Id);

            var postListingModels = posts.Select(post => new PostListingModel
            {
                Id = post.Id,
                Title = post.Title,
                PostContent = post.Content,
                PostImageUrl = string.IsNullOrEmpty(post.ImageUrl) ? null : webrootpathPost + post.ImageUrl,
                Created = post.Created,
                Views = post.Views,
                RepliesCount = post.Replies.Count()
            }).ToList();

            var model = new ProfileModel
            {
                Id = user.Id,
                UserId = user.Id,
                UserName = user.UserName,
                DisplayName = user.DisplayName,
                UserRating = user.Rating.ToString(),
                UserCommentRating = user.CommentRating.ToString(),
                UserPostRating = user.PostRating.ToString(),
                UserDescription = user.UserDescription,
                ProfileImageUrl = string.IsNullOrEmpty(user.ProfileImageUrl) ? "~/img/users/default_image.jpg" : webrootpathUser + user.ProfileImageUrl,
                BannerImageUrl = string.IsNullOrEmpty(user.BannerImageUrl) ? null : webrootpathBanner + user.BannerImageUrl,
                MemberSince = user.MemberSince,

ForumDigitalParadise/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
namespace ForumDigitalParadise.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

ForumDigitalParadise/ViewComponents/LoginWrapperViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ForumDigitalParadise.ViewComponents
{
    public class LoginWrapperViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(new ForumDigitalParadise.Models.User.LoginRegisterViewModel()); });
        }
    }
}

ForumDigitalParadise/ViewComponents/SideNavViewComponent.cs
using Microsoft.AspNetCore.Mvc;

namespace ForumDigitalParadise.ViewComponents
{
    public class SideNavViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.Factory.StartNew(() => { return View(); });
        }
    }
}

ForumDigitalParadise/Views/Shared/_FollowersPartial.cshtml
@model ForumDigitalParadise.Models.Followers.MyFollowersModel
@inject Microsoft.AspNetCore.Identity.UserManager<ForumDigitalParadise.Data.Models.ApplicationUser> UserManager
@inject ForumDigitalParadise.Data.IFollower FollowerService
@inject ForumDigitalParadise.Data.IApplicationUser ApplicationUserService

<div class="MyFollowers-popup">
    <div class="frontPage-position">
        <div class="frontPageLearn">
            <p class="frontPageSubHeading-Myfollowers">
                Your Paradise followers
            </p>
        </div>
    </div>

    <hr style="width: 100%; max-width: 920px; height: 1px; border:none; background-color: #91a5e34d;">

    <div class="Myfollowers-TitleInput">
        <div class="followers-header-search">
            <input type="text" class="searchbar-MyFollowers" placeholder=" " autocomplete="off" />
            <label class="placeholder-myfollowers" for="search">Search Followers</label>
        </div>
    </div>

    <div class="follower-container-index">
        @foreach (var follower in Model.Followers)
        {
            <div class="followers-item">
                <div class="follower-section">
                    <div class="MyFollowers-img">
                        @{
                            var profileImageUrl = string.IsNullOrEmpty(follower.FollowerProfileImageUrl)
                            ? Url.Content("~/img/users/default_image.jpg")
                            : Url.Content("~/img/ProfileImages/" + follower.FollowerProfileImageUrl);
                        }
                        <img src="@profileImageUrl" alt="@follower.FollowerName's Profile Image" class="follower-image" />
                    </div>
                    <div class="follower-info" data-user-id="@follower.FollowerId">
                        <div style="display: flex; justify-content: space-between; align-items: center; width: 350px;">
                            <a asp-controller="Profile" asp-action="Overview" asp-route-id="@follower.FollowerId" class="follower-name">u/@follower.FollowerName</a>
                            @{
                                var currentUser = UserManager.GetUserAsync(User).Result;
                                var isFollowing = FollowerService.IsFollowingAsync(currentUser.Id, follower.FollowerId).Result;
                            }
                            @if (isFollowing)
                            {
                                <button type="button" class="unfollow-button-myfollowers" onclick="MyFollowersunfollowUser('@follower.FollowerId', this)">Unfollow</button>
                            }
                            else
                            {
                                <button type="button" class="follow-back-button-myfollowers" onclick="MyFollowersfollowUser('@follower.FollowerId', this)">Follow back</button>
                            }
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

ForumDigitalParadise/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ForumDigitalParadise</title>
    <link rel="stylesheet" href="~/css/users.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/viewers.css" asp-append-version="true">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/header.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/forum.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Index.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/post.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/profile.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/Inboxes.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/admin.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/search.css" asp-append-version="true" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans&display=swap" rel="stylesheet" asp-append-version="true">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" asp-append-version="true">

    <!-- Preload Ionicons scripts -->
    <link rel="preload" href="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js" as="script" />
    <link rel="preload" href="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js" as="script" />
</head>
<body>
    <div id="myFollowersModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div id="followersContent" class="skeleton">
                <div class="skeleton-circle"></div>
                <div class="skeleton-text"></div>
                <div class="skeleton-text"></div>
                <div class="skeleton-text"></div>
            </div>
        </div>
    </div>
    <div id="mainContent" class="skeleton">
        <div class="skeleton-text"></div>
        <div class="skeleton-text"></div>
        <div class="skeleton-text"></div>
    </div>

    @await Component.InvokeAsync("Header")

    @if (!ViewData.ContainsKey("HideSideNav") || !(bool)ViewData["HideSideNav"])
    {
        @await Component.InvokeAsync("SideNav")
    }

    <div id="myFollowersModal" class="modal">
        <div class="modal-content">
            <span class="close">&times;</span>
            <div id="followersContent">
            </div>
        </div>
    </div>

    @await Component.InvokeAsync("SwitchAccounts")

    @RenderBody()

    @await Component.InvokeAsync("LoginWrapper")

    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/script.js" asp-append-version="true"></script>
    <script src="~/js/User.js" asp-append-version="true"></script>
    <script src="~/js/Side.js" asp-append-version="true"></script>
    <script src="~/js/dropdown.js" asp-append-version="true"></script>
    <script src="~/js/ProfileImage.js" asp-append-version="true"></script>
    <!-- Load Ionicons scripts with async -->
    <script type="module" src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.esm.js" async></script>
    <script nomodule src="https://unpkg.com/ionicons@7.1.0/dist/ionicons/ionicons.js" async></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/microsoft-signalr/6.0.0/signalr.min.js"></script>
    <script>
     
        document.addEventListener("DOMContentLoaded", function () {
            const connection = new signalR.HubConnectionBuilder()
                .withUrl("/notificationHub")
                .build();

            connection.on("ReceiveNotification", function (notificationData) {
                toastr.success(`<span class="toast-message">${notificationData.message}</span><ion-icon class="check-indicator-toaster" name="close-outline"></ion-icon>`);
                loadNotifications();
                fetchUnreadNotificationsCount();
            });

            connection.start().then(function () {
                console.log('SignalR connection established');
                loadNotifications();
                fetchUnreadNotificationsCount();
            }).catch(function (err) {
                console.error('SignalR connection error:', err.toString());
            });

            async function loadNotifications() {
                try {
                    const response = await fetch('/api/notification');

                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }

                    const notifications = await response.json();
                    const notificationsBody = document.getElementById('notificationsBody');
                    notificationsBody.innerHTML = '';

                    if (notifications.length > 0) {
                        for (const notification of notifications) {
                            const notificationElement = document.createElement('div');
                            notificationElement.classList.add('notification-item');

                            const profileImageElement = document.createElement('img');
                            profileImageElement.src = notification.profileImageUrl;
                            profileImageElement.alt = `${notification.username}'s profile picture`;
                            profileImageElement.classList.add('profile-image-notification');

                            const messageContainer = document.createElement('div');
                            messageContainer.classList.add('message-container');

                            const messageAndTimeContainer = document.createElement('div');
                            messageAndTimeContainer.classList.add('message-time-container');

                            const messageElement = document.createElement('span');
                            messageElement.innerHTML = notification.message; 
                            messageElement.classList.add('message-text');

                            const followedAt = new Date(notification.createdAt);
                            const timeAgo = getTimeDifference(followedAt);

                            const timeAgoElement = document.createElement('span');
                            timeAgoElement.textContent = timeAgo;
                            timeAgoElement.classList.add('time-ago');

                            messageAndTimeContainer.appendChild(messageElement);
                            messageAndTimeContainer.appendChild(timeAgoElement);

                            messageContainer.appendChild(messageAndTimeContainer);

                            notificationElement.appendChild(profileImageElement);
                            notificationElement.appendChild(messageContainer);
                            notificationsBody.appendChild(notificationElement);
                        }
                    } else {
                        notificationsBody.innerHTML = '<p>You don\'t have any notifications</p>';
                    }

                    document.getElementById('mainContent').classList.remove('skeleton');
                    document.getElementById('followersContent').classList.remove('skeleton');
                } catch (error) {
                    console.error('Error loading notifications:', error);
                }
            }




            async function fetchUnreadNotificationsCount() {
                try {
                    const response = await fetch('/api/notification/unread-count');

                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }

                    const data = await response.json();
                    const unreadCount = data.unreadCount;
                    const unreadNotificationsCountElement = document.getElementById('unreadNotificationsCount');

                    if (unreadCount > 9) {
                        unreadNotificationsCountElement.textContent = '9+';
                        unreadNotificationsCountElement.style.display = 'inline';
                    } else if (unreadCount > 0) {
                        unreadNotificationsCountElement.textContent = unreadCount.toString();
                        unreadNotificationsCountElement.style.display = 'inline';
                    } else {
                        unreadNotificationsCountElement.style.display = 'none';
                    }
                } catch (error) {
                    console.error('Error fetching unread notifications count:', error);
                }
            }

            async function markAllNotificationsAsRead() {
                try {
                    const response = await fetch('/api/notification/mark-all-as-read', {
                        method: 'POST'
                    });

                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }

                    fetchUnreadNotificationsCount();
                } catch (error) {
                    console.error('Error marking notifications as read:', error);
                }
            }

            setInterval(function () {
                loadNotifications();
                fetchUnreadNotificationsCount();
            }, 30000);

            document.getElementById('notificationIcon').addEventListener('click', function () {
                markAllNotificationsAsRead();
                const unreadNotificationsCountElement = document.getElementById('unreadNotificationsCount');
                unreadNotificationsCountElement.style.display = 'none';
            });
            fetchUnreadNotificationsCount();

            function getTimeDifference(createdTime) {
                const now = new Date();
                const diffMs = now - new Date(createdTime);
                const diffSecs = Math.floor(diffMs / 1000);
                const diffMins = Math.floor(diffSecs / 60);
                const diffHours = Math.floor(diffMins / 60);
                const diffDays = Math.floor(diffHours / 24);
                const diffMonths = Math.floor(diffDays / 30);

                if (diffSecs < 60) {
                    return diffSecs + ' sec.' + (diffSecs > 1 ? '' : '') + ' ago';
                } else if (diffMins < 60) {
                    return diffMins + ' min.' + (diffMins > 1 ? '' : '') + ' ago';
                } else if (diffHours < 24) {
                    return diffHours + ' hr.' + (diffHours > 1 ? '' : '') + ' ago';
                } else if (diffDays < 30) {
                    return diffDays + ' day.' + (diffDays > 1 ? '' : '') + ' ago';
                } else {
                    return diffMonths + ' mo.' + (diffMonths > 1 ? '' : '') + ' ago';
                }
            }
        });

        $(window).on('load', function () {
            var progress = 0;
            var interval = setInterval(function () {
                progress += 10;
                $('#progress-bar').css('width', progress + '%');

                if (progress >= 100) {
                    clearInterval(interval);
                    $('#progress-bar-container').fadeOut('slow', function () {
                        $(this).remove();
                    });
                }
            }, 200);

            toastr.options.positionClass = 'toast-bottom-center';
            toastr.options.showMethod = 'fadeIn';
            toastr.options.hideMethod = 'fadeOut';
            toastr.options.showDuration = 500;
            toastr.options.hideDuration = 300;
            toastr.options.timeOut = 3000;
            toastr.options.extendedTimeOut = 1000;
            toastr.options.toastClass = 'custom-toast';

            var successMessage = '@TempData["SuccessMessage"]';
            if (successMessage) {
                toastr.success('<span class="toast-message">' + successMessage + '</span><ion-icon class="check-indicator-toaster" name="close-outline"></ion-icon>');
            }
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>